////*
/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import conec.Conexao;
import java.sql.Connection;


public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(FramePrincipal.DO_NOTHING_ON_CLOSE);
        this.setExtendedState(MAXIMIZED_BOTH);
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuFunc = new javax.swing.JMenuItem();
        jMenuComp = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuPesqFun = new javax.swing.JMenuItem();
        jMenuPesqComp = new javax.swing.JMenuItem();
        jMenuSds = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBusca = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteForms/Capturar.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 100, 450, 470);

        jLabel2.setText("Desenvolvimento: Unimed Catanduva | Contato: (17) 3531-3100 (Ramal: 3184/3300) | E-Mail: edmundo.neto@unimedcatanduva.com.br / igor@unimedcatanduva.com.br");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 670, 1220, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1420, 730);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, null));

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Add-icon.png"))); // NOI18N
        jMenu6.setText("Cadastrar");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/1482791130_user_male2.png"))); // NOI18N
        jMenuFunc.setText("Funcionarios");
        jMenuFunc.setToolTipText("Cadastrar novos funcionarios");
        jMenuFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuFunc);

        jMenuComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/pcc.png"))); // NOI18N
        jMenuComp.setText("Computadores");
        jMenuComp.setToolTipText("Cadastrar novos computadores");
        jMenuComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuComp);

        jMenuBar2.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/search-icon.png"))); // NOI18N
        jMenu1.setText("Pesquisa");

        jMenuPesqFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Searchicons-search-people2-20.png"))); // NOI18N
        jMenuPesqFun.setText("Funcionarios");
        jMenuPesqFun.setToolTipText("Pesquise os Funcionarios da cooperativa");
        jMenuPesqFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesqFunActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPesqFun);

        jMenuPesqComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/sss.png"))); // NOI18N
        jMenuPesqComp.setText("Computadores");
        jMenuPesqComp.setToolTipText("Pesquise os computadores da cooperativa");
        jMenuPesqComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesqCompActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPesqComp);

        jMenuBar2.add(jMenu1);

        jMenuSds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/controll.png"))); // NOI18N
        jMenuSds.setText("Controle ");
        jMenuSds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSdsActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/control.png"))); // NOI18N
        jMenuItem1.setText("Controle de Equipamentos Unimed");
        jMenuItem1.setToolTipText("Cadastre os Equipamentos para Saída.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSds.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/gear-tools-settings-20.png"))); // NOI18N
        jMenuItem2.setText("Controle de Equipamentos SDS");
        jMenuItem2.setToolTipText("Cadastre os Equipamentos para saída.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSds.add(jMenuItem2);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/vector_66_03-24.png"))); // NOI18N
        jMenuItem6.setText("Pesquisa Equipamentos Bios - Unimed");
        jMenuItem6.setToolTipText("Pesquise os Equipamentos que estão na Bios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuSds.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/vector_66_07-20.png"))); // NOI18N
        jMenuItem7.setText("Pesquisa Equipamentos Bios - SDS");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuSds.add(jMenuItem7);

        jMenuBar2.add(jMenuSds);

        jMenuBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/maintenance.png"))); // NOI18N
        jMenuBusca.setText("Manutenção Preventiva");
        jMenuBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscaActionPerformed(evt);
            }
        });

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/list-32.png"))); // NOI18N
        jMenuItem3.setText("Cadastro de Manutenção");
        jMenuItem3.setToolTipText("Cadastre os Funcionarios que estaram de Ferias no mês");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/emblem-people.png"))); // NOI18N
        jMenuItem4.setText("Buscar Funcionarios/Férias");
        jMenuItem4.setToolTipText("Busque os funcionarios que estão de Férias no mês.");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuItem4);

        jMenuBar2.add(jMenuBusca);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/1484153295_error.png"))); // NOI18N
        jMenu2.setText("Sistema");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/system-log-out-16.png"))); // NOI18N
        jMenuItem8.setText("Sair do Sistema");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncActionPerformed
        jFrameCadastroUsuario usuario = new jFrameCadastroUsuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_jMenuFuncActionPerformed

    private void jMenuCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompActionPerformed
        jFrameCadastroComputadores computador = new jFrameCadastroComputadores();
        computador.setVisible(true);
    }//GEN-LAST:event_jMenuCompActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuPesqFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesqFunActionPerformed
        jFramePesquisaUsuarios pesquisafunc = new jFramePesquisaUsuarios();
        pesquisafunc.setVisible(true);
    }//GEN-LAST:event_jMenuPesqFunActionPerformed

    private void jMenuPesqCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesqCompActionPerformed
        jFramePesquisaComp pesquisacomp = new jFramePesquisaComp();
        pesquisacomp.setVisible(true);
    }//GEN-LAST:event_jMenuPesqCompActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jFrameControleEquipamentoUnimed CadastroEquiUnimed = new jFrameControleEquipamentoUnimed();
        CadastroEquiUnimed.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jPesquisaEquipamentosBios pesquisaEquipamentosBios = new jPesquisaEquipamentosBios();
        pesquisaEquipamentosBios.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jFrameControleEquipametoSds CadastroEquipamentoSDS = new jFrameControleEquipametoSds();
        CadastroEquipamentoSDS.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuSdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSdsActionPerformed

    }//GEN-LAST:event_jMenuSdsActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jFramePesquisaEquipamentoSds PesquisaEquipamentos = new jFramePesquisaEquipamentoSds();
        PesquisaEquipamentos.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jFrameCadManutencao CadastroManutencao = new jFrameCadManutencao();
        CadastroManutencao.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscaActionPerformed

    }//GEN-LAST:event_jMenuBuscaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jFrameBuscarMan Buscar = new jFrameBuscarMan();
        Buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrameConfirmacao Confirma = new FrameConfirmacao();
        Confirma.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuBusca;
    private javax.swing.JMenuItem jMenuComp;
    private javax.swing.JMenuItem jMenuFunc;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuPesqComp;
    private javax.swing.JMenuItem jMenuPesqFun;
    private javax.swing.JMenu jMenuSds;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
