/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import Classes.CadManutencao;
import Classes.cadcomp;
import conec.Conexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

//**
// *
////* @author Edmundo Faria de Oliveira Neto <netofaria18@gmail.com>
//*/
public class jFrameBuscarMan extends javax.swing.JFrame {

    /**
     * Creates new form jFrameBuscarMan
     */
    public jFrameBuscarMan() {
        initComponents();
       findmpreventiva();
        // getRootPane().setDefaultButton(jBtnFiltro);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(jFrameBuscarMan.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
        jTblBuscaManutencao.setSelectionBackground(Color.green);

    }

 
    public Connection getConnection() {
        Connection con = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/manutencao", "root", "");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return con;
    }

    public ArrayList<CadManutencao> listmpreventiva(String ValToSearch) {
        ArrayList<CadManutencao> CadastroList = new ArrayList<>();

        Statement st;
        ResultSet rs;

        try {
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM mpreventiva WHERE Concat(Codigo, Funcionario, Departamento, dataFerias, dataVolta, SelecionaStatus,SelecionaMes,SelecionaAno) LIKE ('%" + ValToSearch + "%')";
            rs = st.executeQuery(searchQuery);

//"SELECT * FROM mpreventiva WHERE CONCAT(Codigo, Funcionario, Departamento, DataFerias,DataVolta,SelecionaStatus,SelecionaMes,SelecionaAno) LIKE ('%" + ValToSearch + "%')";
            CadManutencao Mpreventiva;

            while (rs.next()) {
                Mpreventiva = new CadManutencao(
                        rs.getInt("Codigo"),
                        rs.getString("Funcionario"),
                        rs.getString("Departamento"),
                        rs.getString("dataFerias"),
                        rs.getString("dataVolta"),
                        rs.getString("SelecionaStatus"),
                        rs.getString("SelecionaMes"),
                        rs.getString("SelecionaAno")
                );
                CadastroList.add(Mpreventiva);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return CadastroList;
    }

    public void findmpreventiva() {
        ArrayList<CadManutencao> Cadastros = listmpreventiva(jTxtNomeBusca.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Codigo", "Funcionario", "Departamento", "Data Saida", "Data Volta", "Status", "Mes", "Ano"});
        Object[] row = new Object[8];

        for (int i = 0; i < Cadastros.size(); i++) {

            row[0] = Cadastros.get(i).getCodigo();
            row[1] = Cadastros.get(i).getFuncionario();
            row[2] = Cadastros.get(i).getDepartamento();
            row[3] = Cadastros.get(i).getDataFerias();
            row[4] = Cadastros.get(i).getDataVolta();
            row[5] = Cadastros.get(i).getSelecionaStatus();
            row[6] = Cadastros.get(i).getSelecionaMes();
            row[7] = Cadastros.get(i).getSelecionaAno();

            model.addRow(row);
        }
        jTblBuscaManutencao.setModel(model);

       int somaLinhas = jTblBuscaManutencao.getRowCount();
       jTxtContador.setText(Integer.toString(somaLinhas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("manutencao?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        mpreventivaQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mpreventiva m");
        mpreventivaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mpreventivaQuery.getResultList();
        cadastrocomputadorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrocomputador c");
        cadastrocomputadorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrocomputadorQuery.getResultList();
        mpreventivaQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mpreventiva m");
        mpreventivaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mpreventivaQuery1.getResultList();
        mpreventivaQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mpreventiva m");
        mpreventivaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mpreventivaQuery2.getResultList();
        mpreventivaQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mpreventiva m");
        mpreventivaList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mpreventivaQuery3.getResultList();
        jPanel2 = new javax.swing.JPanel();
        jBtnRelatorioPesqManutencao = new javax.swing.JButton();
        jAtualizarCadManutencao = new javax.swing.JButton();
        jCodigoBusca = new javax.swing.JLabel();
        jTxtCodigoCadManutencao = new javax.swing.JTextField();
        jTxtNomeBusca = new javax.swing.JTextField();
        jBtnSairCadManu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblBuscaManutencao = new javax.swing.JTable();
        jTxtContador = new javax.swing.JTextField();
        jCodigoBusca1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Funcionarios Férias"));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnRelatorioPesqManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/distributor-report-icon.png"))); // NOI18N
        jBtnRelatorioPesqManutencao.setToolTipText("Relatório");
        jBtnRelatorioPesqManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelatorioPesqManutencaoActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnRelatorioPesqManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        jAtualizarCadManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/atualizar.png"))); // NOI18N
        jAtualizarCadManutencao.setToolTipText("Atualizar");
        jAtualizarCadManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarCadManutencaoActionPerformed(evt);
            }
        });
        jPanel2.add(jAtualizarCadManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, -1));

        jCodigoBusca.setText("computadores ");
        jPanel2.add(jCodigoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jTxtCodigoCadManutencao.setEditable(false);
        jTxtCodigoCadManutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCodigoCadManutencaoMouseClicked(evt);
            }
        });
        jTxtCodigoCadManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoCadManutencaoActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtCodigoCadManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 32, 20));

        jTxtNomeBusca.setToolTipText("Digite algo para fazer a busca");
        jTxtNomeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNomeBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtNomeBuscaKeyReleased(evt);
            }
        });
        jPanel2.add(jTxtNomeBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 630, -1));

        jBtnSairCadManu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Log Out.png"))); // NOI18N
        jBtnSairCadManu.setToolTipText("Sair");
        jBtnSairCadManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairCadManuActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSairCadManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, -1, -1));

        jLabel2.setText("Filtro");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 50, -1));

        jTblBuscaManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Data Ferias", "Data Volta", "Departamento", "Funcionario", "Seleciona Ano", "Seleciona Mes", "Seleciona Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblBuscaManutencao.setColumnSelectionAllowed(true);
        jTblBuscaManutencao.setEnabled(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mpreventivaList3, jTblBuscaManutencao);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataFerias}"));
        columnBinding.setColumnName("Data Ferias");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataVolta}"));
        columnBinding.setColumnName("Data Volta");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento}"));
        columnBinding.setColumnName("Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${funcionario}"));
        columnBinding.setColumnName("Funcionario");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${selecionaAno}"));
        columnBinding.setColumnName("Seleciona Ano");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${selecionaMes}"));
        columnBinding.setColumnName("Seleciona Mes");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${selecionaStatus}"));
        columnBinding.setColumnName("Seleciona Status");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTblBuscaManutencao);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1120, 490));

        jTxtContador.setEditable(false);
        jPanel2.add(jTxtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 50, -1));

        jCodigoBusca1.setText("Código");
        jPanel2.add(jCodigoBusca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRelatorioPesqManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelatorioPesqManutencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRelatorioPesqManutencaoActionPerformed

    private void jBtnSairCadManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairCadManuActionPerformed
        jFrameBuscarMan.this.dispose();
    }//GEN-LAST:event_jBtnSairCadManuActionPerformed

    private void jTxtNomeBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNomeBuscaKeyReleased


    }//GEN-LAST:event_jTxtNomeBuscaKeyReleased

    private void jTxtNomeBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNomeBuscaKeyPressed
         findmpreventiva();
    }//GEN-LAST:event_jTxtNomeBuscaKeyPressed

    private void jAtualizarCadManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarCadManutencaoActionPerformed
        jFrameCadManutencao CadastroManutencao = new jFrameCadManutencao();
        CadastroManutencao.setVisible(true);
    }//GEN-LAST:event_jAtualizarCadManutencaoActionPerformed

    private void jTxtCodigoCadManutencaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCodigoCadManutencaoMouseClicked

    }//GEN-LAST:event_jTxtCodigoCadManutencaoMouseClicked

    private void jTxtCodigoCadManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoCadManutencaoActionPerformed

    }//GEN-LAST:event_jTxtCodigoCadManutencaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameBuscarMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameBuscarMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameBuscarMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameBuscarMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameBuscarMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<PktClassesCriadasAutomatico.Cadastrocomputador> cadastrocomputadorList;
    private javax.persistence.Query cadastrocomputadorQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jAtualizarCadManutencao;
    private javax.swing.JButton jBtnRelatorioPesqManutencao;
    private javax.swing.JButton jBtnSairCadManu;
    private javax.swing.JLabel jCodigoBusca;
    private javax.swing.JLabel jCodigoBusca1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblBuscaManutencao;
    private javax.swing.JTextField jTxtCodigoCadManutencao;
    private javax.swing.JTextField jTxtContador;
    private javax.swing.JTextField jTxtNomeBusca;
    private java.util.List<PktClassesCriadasAutomatico.Mpreventiva> mpreventivaList;
    private java.util.List<PktClassesCriadasAutomatico.Mpreventiva> mpreventivaList1;
    private java.util.List<PktClassesCriadasAutomatico.Mpreventiva> mpreventivaList2;
    private java.util.List<PktClassesCriadasAutomatico.Mpreventiva> mpreventivaList3;
    private javax.persistence.Query mpreventivaQuery;
    private javax.persistence.Query mpreventivaQuery1;
    private javax.persistence.Query mpreventivaQuery2;
    private javax.persistence.Query mpreventivaQuery3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private static class sorter {

        private static void setRowFilter(Object object) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public sorter() {
        }
    }
}
