/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import conec.Conexao;
import java.awt.Color;
import java.sql.Connection;

//**
 /*
 //* @author Edmundo Faria de Oliveira Neto <netofaria18@gmail.c>om>
 /*/
public class jFramePesquisaEquipamentoSds extends javax.swing.JFrame {

    /**
     * Creates new form jFramePesquisaEquipamentoSds
     */
    public jFramePesquisaEquipamentoSds() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(jFramePesquisaEquipamentoSds.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
         jTblSds.setSelectionBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("manutencao?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        controlequisdsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Controlequisds c");
        controlequisdsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : controlequisdsQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoSds = new javax.swing.JTextField();
        jTxtMostraSds = new javax.swing.JTextField();
        jBtnAlterarPesqEquipBiosSds = new javax.swing.JButton();
        jBtnRelatorio = new javax.swing.JButton();
        jBtnSairPesqEquipBiosSds = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSds = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Equipamentos Bios - SDS"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, -1));

        jTxtCodigoSds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoSdsActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCodigoSds, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, -1));
        jPanel1.add(jTxtMostraSds, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 540, -1));

        jBtnAlterarPesqEquipBiosSds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/atualizar.png"))); // NOI18N
        jBtnAlterarPesqEquipBiosSds.setToolTipText("Alterar");
        jPanel1.add(jBtnAlterarPesqEquipBiosSds, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 30, 30));

        jBtnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/distributor-report-icon.png"))); // NOI18N
        jPanel1.add(jBtnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 30, 30));

        jBtnSairPesqEquipBiosSds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Log Out.png"))); // NOI18N
        jBtnSairPesqEquipBiosSds.setToolTipText("Sair");
        jBtnSairPesqEquipBiosSds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairPesqEquipBiosSdsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSairPesqEquipBiosSds, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 30, 30));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controlequisdsList, jTblSds);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codEquip}"));
        columnBinding.setColumnName("Cod Equip");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patrimonio}"));
        columnBinding.setColumnName("Patrimonio");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${equipamento}"));
        columnBinding.setColumnName("Equipamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento}"));
        columnBinding.setColumnName("Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataEnvio}"));
        columnBinding.setColumnName("Data Envio");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataRetorno}"));
        columnBinding.setColumnName("Data Retorno");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${selecione}"));
        columnBinding.setColumnName("Selecione");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${orcamento}"));
        columnBinding.setColumnName("Orcamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${centroCusto}"));
        columnBinding.setColumnName("Centro Custo");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTblSds);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 878, 519));

        jLabel2.setText("Buscar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoSdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoSdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoSdsActionPerformed

    private void jBtnSairPesqEquipBiosSdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairPesqEquipBiosSdsActionPerformed
        jFramePesquisaEquipamentoSds.this.dispose();
    }//GEN-LAST:event_jBtnSairPesqEquipBiosSdsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaEquipamentoSds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaEquipamentoSds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaEquipamentoSds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaEquipamentoSds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePesquisaEquipamentoSds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<PktClassesCriadasAutomatico.Controlequisds> controlequisdsList;
    private javax.persistence.Query controlequisdsQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBtnAlterarPesqEquipBiosSds;
    private javax.swing.JButton jBtnRelatorio;
    private javax.swing.JButton jBtnSairPesqEquipBiosSds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblSds;
    private javax.swing.JTextField jTxtCodigoSds;
    private javax.swing.JTextField jTxtMostraSds;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
