/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import Classes.caduser;
import conec.Conexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

//**
//*
//* @author Sammy Guergachi <sguergachi at gmail.com>
// */
public class jFramePesquisaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form jFramePesquisaUsuarios
     */
    public jFramePesquisaUsuarios() {
        initComponents();
        findcaduser();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(jFramePesquisaComp.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
        jTblUser.setSelectionBackground(Color.green);
    }

    public Connection getConnection() {
        Connection con = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/manutencao", "root", "");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return con;
    }

    public ArrayList<caduser> listcaduser(String ValToSearch) {
        ArrayList<caduser> CadastroList = new ArrayList<>();

        Statement st;
        ResultSet rs;

        try {
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM cadastrofuncionario WHERE Concat(CodUser, NomeFunc, Funcao, Departamento) LIKE ('%" + ValToSearch + "%')";
            rs = st.executeQuery(searchQuery);

//"SELECT * FROM mpreventiva WHERE CONCAT(Codigo, Funcionario, Departamento, DataFerias,DataVolta,SelecionaStatus,SelecionaMes,SelecionaAno) LIKE ('%" + ValToSearch + "%')";
            caduser cadastrouser;

            while (rs.next()) {
                cadastrouser = new caduser(
                        rs.getInt("CodUser"),
                        rs.getString("NomeFunc"),
                        rs.getString("Funcao"),
                        rs.getString("Departamento"));
                CadastroList.add(cadastrouser);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return CadastroList;
    }

    public void findcaduser() {
        ArrayList<caduser> Cadastros = listcaduser(jTxtViewPesquisaFunc.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Codigo", "Funcionario", "Funcão", "Departamento"});
        Object[] row = new Object[8];

        for (int i = 0; i < Cadastros.size(); i++) {

            row[0] = Cadastros.get(i).getCodUser();
            row[1] = Cadastros.get(i).getNomeFunc();
            row[2] = Cadastros.get(i).getFuncao();
            row[3] = Cadastros.get(i).getDepartamento();

            model.addRow(row);
        }
        jTblUser.setModel(model);

        //int somaLinhas = jTblUser.getRowCount();
        //jTxtContador.setText(Integer.toString(somaLinhas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("manutencao?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        cadastrocomputadorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrocomputador c");
        cadastrocomputadorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrocomputadorQuery.getResultList();
        cadastrofuncionarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery.getResultList();
        cadastrofuncionarioQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery1.getResultList();
        cadastrofuncionarioQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery2.getResultList();
        cadastrofuncionarioQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery3.getResultList();
        cadastrofuncionarioQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery4.getResultList();
        cadastrofuncionarioQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery5.getResultList();
        cadastrofuncionarioQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cadastrofuncionario c");
        cadastrofuncionarioList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cadastrofuncionarioQuery6.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jBtnAlterarFunc = new javax.swing.JButton();
        jBtnRelatorioPesqFunc = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jTxtViewPesquisaFunc = new javax.swing.JTextField();
        jTxtCodPesquisaFunc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jBtnAlterarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/atualizar.png"))); // NOI18N
        jBtnAlterarFunc.setToolTipText("Atualizar");
        jBtnAlterarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarFuncActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 30, 30));

        jBtnRelatorioPesqFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/distributor-report-icon.png"))); // NOI18N
        jBtnRelatorioPesqFunc.setToolTipText("Relatório");
        jBtnRelatorioPesqFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelatorioPesqFuncActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRelatorioPesqFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 30, 30));

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Log Out.png"))); // NOI18N
        jBtnSair.setToolTipText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 30, 30));

        jTxtViewPesquisaFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtViewPesquisaFuncKeyPressed(evt);
            }
        });
        getContentPane().add(jTxtViewPesquisaFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 400, -1));

        jTxtCodPesquisaFunc.setEditable(false);
        getContentPane().add(jTxtCodPesquisaFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 29, 20));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("Buscar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cadastrofuncionarioList6, jTblUser);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTblUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 560, 420));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarFuncActionPerformed
        jFrameCadastroUsuario computador = new jFrameCadastroUsuario();
        computador.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarFuncActionPerformed

    private void jBtnRelatorioPesqFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelatorioPesqFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRelatorioPesqFuncActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        jFramePesquisaUsuarios.this.dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jTxtViewPesquisaFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtViewPesquisaFuncKeyPressed
        findcaduser();
    }//GEN-LAST:event_jTxtViewPesquisaFuncKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePesquisaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePesquisaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<PktClassesCriadasAutomatico.Cadastrocomputador> cadastrocomputadorList;
    private javax.persistence.Query cadastrocomputadorQuery;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList1;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList2;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList3;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList4;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList5;
    private java.util.List<PktClassesCriadasAutomatico.Cadastrofuncionario> cadastrofuncionarioList6;
    private javax.persistence.Query cadastrofuncionarioQuery;
    private javax.persistence.Query cadastrofuncionarioQuery1;
    private javax.persistence.Query cadastrofuncionarioQuery2;
    private javax.persistence.Query cadastrofuncionarioQuery3;
    private javax.persistence.Query cadastrofuncionarioQuery4;
    private javax.persistence.Query cadastrofuncionarioQuery5;
    private javax.persistence.Query cadastrofuncionarioQuery6;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBtnAlterarFunc;
    private javax.swing.JButton jBtnRelatorioPesqFunc;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblUser;
    private javax.swing.JTextField jTxtCodPesquisaFunc;
    private javax.swing.JTextField jTxtViewPesquisaFunc;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
