/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import Classes.CadManutencao;
import conec.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.M;
import javax.swing.JOptionPane;

//**
//*
//* @author Edmundo Faria de Oliveira Neto <netofaria18@gmail.com>
//*/
public class jFrameCadManutencao extends javax.swing.JFrame {

    CadManutencao mp;

    /**
     * Creates new form jFrameCadManutencao
     */
    public jFrameCadManutencao() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(jFrameCadManutencao.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        //conexão
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("manutencao?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        mpreventivaQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mpreventiva m");
        mpreventivaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mpreventivaQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoManutencao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFuncionarioManutencao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtDepartamentoManutencao = new javax.swing.JTextField();
        jCbSelecionarManutencao = new javax.swing.JComboBox<>();
        jSairManutencao = new javax.swing.JButton();
        jBtnSalvarManutencao = new javax.swing.JButton();
        jBtnPesquisa = new javax.swing.JButton();
        jCbMes = new javax.swing.JComboBox<>();
        jCbAno = new javax.swing.JComboBox<>();
        jBtnAtualizarManutencao1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Atualiza = new javax.swing.JButton();
        jTxtDataFimManutencao = new javax.swing.JFormattedTextField();
        jTxtDataInicialManutencao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção Preventiva"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Férias - Fim");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 117, -1));

        jTxtCodigoManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoManutencaoActionPerformed(evt);
            }
        });
        jTxtCodigoManutencao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCodigoManutencaoKeyReleased(evt);
            }
        });
        jPanel1.add(jTxtCodigoManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, -1));

        jLabel2.setText("Código");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, -1));

        jLabel3.setText("Funcionário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 82, -1));
        jPanel1.add(jTxtFuncionarioManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, -1));

        jLabel4.setText("Departamento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 88, -1));

        jLabel5.setText("Data Férias - Inicio ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 115, -1));
        jPanel1.add(jTxtDepartamentoManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, -1));

        jCbSelecionarManutencao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Conclúido", "A Fazer", " ", " ", " " }));
        jPanel1.add(jCbSelecionarManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, -1));

        jSairManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Log Out.png"))); // NOI18N
        jSairManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairManutencaoActionPerformed(evt);
            }
        });
        jPanel1.add(jSairManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 30, 40));

        jBtnSalvarManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Save-icon.png"))); // NOI18N
        jBtnSalvarManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarManutencaoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalvarManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 30, 40));

        jBtnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/search-icon.png"))); // NOI18N
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 30, 40));

        jCbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jPanel1.add(jCbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, -1));

        jCbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "2016", "2017", "2018", "2019", "2020", "2021" }));
        jPanel1.add(jCbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, -1));

        jBtnAtualizarManutencao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/emblem-people.png"))); // NOI18N
        jBtnAtualizarManutencao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarManutencao1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAtualizarManutencao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 30, 40));

        jLabel6.setText(" * aaaa/mm/dd");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 140, 20));

        jLabel7.setText("* aaaa/mm/dd  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 140, 20));

        Atualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/black_2_audio_simple_repeat_2-32.png"))); // NOI18N
        Atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizaActionPerformed(evt);
            }
        });
        jPanel1.add(Atualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 30, 40));

        try {
            jTxtDataFimManutencao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jTxtDataFimManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, -1));

        try {
            jTxtDataInicialManutencao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jTxtDataInicialManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSairManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairManutencaoActionPerformed
        jFrameCadManutencao.this.dispose();
    }//GEN-LAST:event_jSairManutencaoActionPerformed

    private void jBtnSalvarManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarManutencaoActionPerformed

        //metodo para salvar
        mp = new CadManutencao(Integer.parseInt(jTxtCodigoManutencao.getText()),
                jTxtFuncionarioManutencao.getText(),
                jTxtDepartamentoManutencao.getText(),
                (jTxtDataInicialManutencao.getText()),
                (jTxtDataFimManutencao.getText()),
                jCbSelecionarManutencao.getSelectedItem().toString(),
                jCbMes.getSelectedItem().toString(),
                jCbAno.getSelectedItem().toString());

        //mensagem ao sair
        JOptionPane.showMessageDialog(this, "salvo com sucesso!");

//----------- limpar
        jTxtCodigoManutencao.setText("");
        jTxtFuncionarioManutencao.setText("");
        jTxtDepartamentoManutencao.setText("");
        jTxtDataInicialManutencao.setText("");
        jTxtDataFimManutencao.setText("");
        jCbSelecionarManutencao.setSelectedItem("");
        jCbMes.setSelectedItem("");
        jCbAno.setSelectedItem("");

        mp.Save();


    }//GEN-LAST:event_jBtnSalvarManutencaoActionPerformed

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        jFrameBuscarMan Buscar = new jFrameBuscarMan();
        Buscar.setVisible(true);


    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    private void jTxtCodigoManutencaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoManutencaoKeyReleased

    }//GEN-LAST:event_jTxtCodigoManutencaoKeyReleased

    private void jBtnAtualizarManutencao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarManutencao1ActionPerformed

        try {
            mp = new CadManutencao(Integer.parseInt(jTxtCodigoManutencao.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(jFrameCadManutencao.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTxtFuncionarioManutencao.setText(mp.getFuncionario());
        jTxtDepartamentoManutencao.setText(mp.getDepartamento());
        jTxtDataInicialManutencao.setText(mp.getDataFerias());
        jTxtDataFimManutencao.setText(mp.getDataVolta());
        jCbSelecionarManutencao.setSelectedItem(mp.getSelecionaStatus());
        jCbMes.setSelectedItem(mp.getSelecionaMes());
        jCbAno.setSelectedItem(mp.getSelecionaAno());


    }//GEN-LAST:event_jBtnAtualizarManutencao1ActionPerformed

    private void jTxtCodigoManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoManutencaoActionPerformed

        Random gerador = new Random();

        //pega numeros randomicos até 100, passa para uma variavel String
        String numero = String.valueOf((gerador.nextInt(10000)));
        //seta o jTextField
        jTxtCodigoManutencao.setText(numero);


    }//GEN-LAST:event_jTxtCodigoManutencaoActionPerformed

    private void AtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizaActionPerformed

        Conexao C = new Conexao();
        Connection con = C.getCon();
        ResultSet rs = null;
        PreparedStatement stmt = null;

        try {
           // 
            stmt = con.prepareStatement ( "UPDATE  mpreventiva SET Funcionario = ? ,Departamento = ? ,DataFerias = ? ,DataVolta = ? ,SelecionaStatus = ? ,SelecionaMes = ? ,SelecionaAno = ? where codigo = ? ");
            stmt.setString(1, jTxtFuncionarioManutencao.getText());
            stmt.setString(2, jTxtDepartamentoManutencao.getText());
            stmt.setString(3, jTxtDataInicialManutencao.getText());
            stmt.setString(4, jTxtDataFimManutencao.getText());
            stmt.setString(5, (String) jCbSelecionarManutencao.getSelectedItem());
            stmt.setString(6, (String) jCbMes.getSelectedItem());
            stmt.setString(7, (String) jCbAno.getSelectedItem());
            stmt.setString(8, jTxtCodigoManutencao.getText());
            stmt.executeUpdate();
   
            
             stmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            
        }
    }//GEN-LAST:event_AtualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameCadManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameCadManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameCadManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameCadManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and dispjBtnSalvarManutencaoform */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameCadManutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualiza;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBtnAtualizarManutencao1;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JButton jBtnSalvarManutencao;
    private javax.swing.JComboBox<String> jCbAno;
    private javax.swing.JComboBox<String> jCbMes;
    private javax.swing.JComboBox<String> jCbSelecionarManutencao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSairManutencao;
    private javax.swing.JTextField jTxtCodigoManutencao;
    private javax.swing.JFormattedTextField jTxtDataFimManutencao;
    private javax.swing.JFormattedTextField jTxtDataInicialManutencao;
    private javax.swing.JTextField jTxtDepartamentoManutencao;
    private javax.swing.JTextField jTxtFuncionarioManutencao;
    private java.util.List<PktClassesCriadasAutomatico.Mpreventiva> mpreventivaList;
    private javax.persistence.Query mpreventivaQuery;
    // End of variables declaration//GEN-END:variables
}
