/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteForms;

import Classes.ControlEquiUnimed;
import conec.Conexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class jPesquisaEquipamentosBios extends javax.swing.JFrame {

    /**
     * Creates new form jPesquisaEquipamentosBios
     */
    public jPesquisaEquipamentosBios() {
        initComponents();
        findControlEquiUnimed();
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(jFramePesquisaComp.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        Conexao conexao = new Conexao();
        Connection C = conexao.getCon();
        System.out.println("conexao ok!");
        jTblUnimed.setSelectionBackground(Color.green);
    }

    public Connection getConnection() {
        Connection con = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/manutencao", "root", "");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return con;
    }

    public ArrayList<ControlEquiUnimed> listBiosUnimed(String ValToSearch) {
        ArrayList<ControlEquiUnimed> CadastroList = new ArrayList<>();

        Statement st;
        ResultSet rs;

        try {
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM controleequipamentounimed WHERE Concat (CodEquip, Patrimonio, Equipamento, Modelo, Departamento, DataEnvio, DataRetorno, Selecione, orcamento, CentroCusto) LIKE ('%" + ValToSearch + "%')";
            rs = st.executeQuery(searchQuery);

            ControlEquiUnimed pesquisaBios;

            while (rs.next()) {
                pesquisaBios = new ControlEquiUnimed(
                        rs.getInt("CodEquip"),
                        rs.getInt("Patrimonio"),
                        rs.getString("Equipamento"),
                        rs.getString("Modelo"),
                        rs.getString("Departamento"),
                        rs.getString("DataEnvio"),
                        rs.getString("DataRetorno"),
                        rs.getString("Selecione"),
                        rs.getFloat("orcamento"),
                        rs.getInt("CentroCusto"));
                CadastroList.add(pesquisaBios);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return CadastroList;
    }

    public void findControlEquiUnimed() {
        ArrayList<ControlEquiUnimed> listcontrolBios = listBiosUnimed(jTxtMostraUnimed.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Codigo", "Patrimonio", "Equipamento", "Modelo", "Departamento", "Data Envio", "Data Retorno", "Status", "Orcamento", "Centro de Custo"});
        Object[] row = new Object[10];

        for (int i = 0; i < listcontrolBios.size(); i++) {

            row[0] = listcontrolBios.get(i).getCodEquip();
            row[1] = listcontrolBios.get(i).getPatrimonio();
            row[2] = listcontrolBios.get(i).getEquipamento();
            row[3] = listcontrolBios.get(i).getModelo();
            row[4] = listcontrolBios.get(i).getDepartamento();
            row[5] = listcontrolBios.get(i).getDataEnvio();
            row[6] = listcontrolBios.get(i).getDataRetorno();
            row[7] = listcontrolBios.get(i).getSelecione();
            row[8] = listcontrolBios.get(i).getOrcamento();
            row[9] = listcontrolBios.get(i).getCentroCusto();

            model.addRow(row);
        }
        jTblUnimed.setModel(model);

        //int somaLinhas = jTblUser.getRowCount();
        //jTxtContador.setText(Integer.toString(somaLinhas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("manutencao?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        controleequipamentounimedQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Controleequipamentounimed c");
        controleequipamentounimedList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : controleequipamentounimedQuery.getResultList();
        controleequipamentounimedQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Controleequipamentounimed c");
        controleequipamentounimedList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : controleequipamentounimedQuery1.getResultList();
        controleequipamentounimedQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Controleequipamentounimed c");
        controleequipamentounimedList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : controleequipamentounimedQuery2.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoUnimed = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblUnimed = new javax.swing.JTable();
        jTxtMostraUnimed = new javax.swing.JTextField();
        jBtnSairPesqEquipBiosUnimed = new javax.swing.JButton();
        jBtnAlterarPesqEquipBiosUnimed = new javax.swing.JButton();
        jBtnRelatorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtContador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Equipamentos Bios - Unimed "));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, -1));

        jTxtCodigoUnimed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoUnimedActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCodigoUnimed, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, controleequipamentounimedList2, jTblUnimed);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codEquip}"));
        columnBinding.setColumnName("Cod Equip");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patrimonio}"));
        columnBinding.setColumnName("Patrimonio");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${equipamento}"));
        columnBinding.setColumnName("Equipamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento}"));
        columnBinding.setColumnName("Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataEnvio}"));
        columnBinding.setColumnName("Data Envio");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataRetorno}"));
        columnBinding.setColumnName("Data Retorno");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${selecione}"));
        columnBinding.setColumnName("Selecione");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${orcamento}"));
        columnBinding.setColumnName("Orcamento");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${centroCusto}"));
        columnBinding.setColumnName("Centro Custo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTblUnimed);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1000, 430));

        jTxtMostraUnimed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtMostraUnimedKeyPressed(evt);
            }
        });
        jPanel1.add(jTxtMostraUnimed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 640, -1));

        jBtnSairPesqEquipBiosUnimed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/Log Out.png"))); // NOI18N
        jBtnSairPesqEquipBiosUnimed.setToolTipText("Sair");
        jBtnSairPesqEquipBiosUnimed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairPesqEquipBiosUnimedActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSairPesqEquipBiosUnimed, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 30, 30));

        jBtnAlterarPesqEquipBiosUnimed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/atualizar.png"))); // NOI18N
        jBtnAlterarPesqEquipBiosUnimed.setToolTipText("Alterar");
        jBtnAlterarPesqEquipBiosUnimed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarPesqEquipBiosUnimedActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAlterarPesqEquipBiosUnimed, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 30, 30));

        jBtnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PktImagens/distributor-report-icon.png"))); // NOI18N
        jPanel1.add(jBtnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 30, 30));

        jLabel2.setText("Buscar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jTxtContador.setEditable(false);
        jPanel1.add(jTxtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoUnimedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoUnimedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoUnimedActionPerformed

    private void jBtnSairPesqEquipBiosUnimedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairPesqEquipBiosUnimedActionPerformed
        jPesquisaEquipamentosBios.this.dispose();


    }//GEN-LAST:event_jBtnSairPesqEquipBiosUnimedActionPerformed

    private void jBtnAlterarPesqEquipBiosUnimedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarPesqEquipBiosUnimedActionPerformed
        jFrameControleEquipamentoUnimed CadastroEquiUnimed = new jFrameControleEquipamentoUnimed();
        CadastroEquiUnimed.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarPesqEquipBiosUnimedActionPerformed

    private void jTxtMostraUnimedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtMostraUnimedKeyPressed
        findControlEquiUnimed();

    }//GEN-LAST:event_jTxtMostraUnimedKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javajBtnRelatorioel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPesquisaEquipamentosBios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPesquisaEquipamentosBios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPesquisaEquipamentosBios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPesquisaEquipamentosBios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPesquisaEquipamentosBios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<PktClassesCriadasAutomatico.Controleequipamentounimed> controleequipamentounimedList;
    private java.util.List<PktClassesCriadasAutomatico.Controleequipamentounimed> controleequipamentounimedList1;
    private java.util.List<PktClassesCriadasAutomatico.Controleequipamentounimed> controleequipamentounimedList2;
    private javax.persistence.Query controleequipamentounimedQuery;
    private javax.persistence.Query controleequipamentounimedQuery1;
    private javax.persistence.Query controleequipamentounimedQuery2;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBtnAlterarPesqEquipBiosUnimed;
    private javax.swing.JButton jBtnRelatorio;
    private javax.swing.JButton jBtnSairPesqEquipBiosUnimed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblUnimed;
    private javax.swing.JTextField jTxtCodigoUnimed;
    private javax.swing.JTextField jTxtContador;
    private javax.swing.JTextField jTxtMostraUnimed;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
